### ISSUE TITLE
final polishes

### ISSUE THREAD

**Issue by edenbrack** [howwegettonext/2017databreaches#37]
- [x] padding between key, title, x-axis

- [x] icons centered above email sign up

- [x] padding between email sign up and series image

- [x] leave out Storythings mentions

- [x] URL howwegettonext.com/2017databreaches

**Comment by duncangeere** [comment]
vis.howwegettonext.com/2017databreaches

**Comment by duncangeere** [comment]
I had a spare moment so took out the Storythings mentions.

**Comment by duncangeere** [comment]
I think all of these are complete now.
